import OpenAI from 'openai'

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY || 'sk-placeholder'
})

export async function generateInsight(answers, scores) {
  const prompt = buildInsightPrompt(answers, scores)
  
  try {
    const completion = await openai.chat.completions.create({
      model: 'gpt-4',
      messages: [
        {
          role: 'system',
          content: `You are an expert wellness coach with deep knowledge in sleep science, nutrition, exercise physiology, mental health, and stress management. 
Your role is to analyze wellness assessment data and provide personalized, actionable insights.
Always be supportive, never diagnostic (you are not a medical professional), and focus on practical improvements.
Format your response with clear sections for each wellness dimension.`
        },
        {
          role: 'user',
          content: prompt
        }
      ],
      max_tokens: 1500,
      temperature: 0.7
    })

    return completion.choices[0].message.content
  } catch (error) {
    console.error('OpenAI API error:', error)
    // Fallback to template response if API fails
    return generateFallbackInsight(answers, scores)
  }
}

function buildInsightPrompt(answers, scores) {
  const scoreSummary = Object.entries(scores)
    .map(([cat, score]) => `${cat}: ${score}/100`)
    .join('\n')

  const answerSummary = Object.entries(answers)
    .map(([key, value]) => `${key}: ${value}`)
    .join('\n')

  return `Analyze the following wellness assessment results and provide personalized insights:

WELLNESS SCORES:
${scoreSummary}

ASSESSMENT ANSWERS:
${answerSummary}

Please provide:
1. An overall wellness summary
2. Key strengths to celebrate
3. Areas for improvement with specific, actionable recommendations
4. Top 3 priority actions they should take this week
5. A motivational closing message

Keep recommendations practical and tailored to the specific scores provided.`
}

function generateFallbackInsight(answers, scores) {
  const overall = Object.values(scores).length > 0
    ? Math.round(Object.values(scores).reduce((a, b) => a + b, 0) / Object.values(scores).length)
    : 0

  const getRecommendations = (category, score) => {
    if (score >= 80) return `Your ${category.toLowerCase()} is excellent! Keep up the great work.`
    if (score >= 60) return `Your ${category.toLowerCase()} is good. Consider small improvements to optimize further.`
    return `Focus on improving your ${category.toLowerCase()}. Small changes can make a big difference.`
  }

  return `# Your AI Wellness Report

## Overall Wellness Score: ${overall}/100

### Your Strengths
${Object.entries(scores)
  .filter(([_, s]) => s >= 70)
  .map(([cat, score]) => `- ${cat} (${score}/100): Great job maintaining this area!`)
  .join('\n') || '- No specific strengths identified yet'}

### Areas for Improvement
${Object.entries(scores)
  .filter(([_, s]) => s < 70)
  .map(([cat, score]) => `- ${cat} (${score}/100): ${getRecommendations(cat, score)}`)
  .join('\n') || '- You are doing well in all areas!'}

### Your Top 3 Priority Actions
1. ${scores.Sleep < 70 ? 'Establish a consistent sleep schedule with 7-8 hours nightly' : 'Maintain your excellent sleep habits'}
2. ${scores.Exercise < 70 ? 'Aim for at least 30 minutes of physical activity most days' : 'Keep up your active lifestyle'}
3. ${scores.Mental_Health < 70 ? 'Practice daily mindfulness or stress-reducing activities' : 'Continue supporting your mental wellbeing'}

### Final Thoughts
Remember, wellness is a journey, not a destination. Small consistent improvements lead to lasting change. You're taking an important step by completing this assessment!

---
*This insight was generated by AI Wellness. For medical concerns, please consult a healthcare professional.*`
}

export async function generatePremiumInsight(basicInsight, answers, scores) {
  const prompt = buildPremiumPrompt(basicInsight, answers, scores)
  
  try {
    const completion = await openai.chat.completions.create({
      model: 'gpt-4',
      messages: [
        {
          role: 'system',
          content: `You are an elite wellness coach providing premium, in-depth analysis.
You provide comprehensive, personalized guidance with specific action plans, meal suggestions, exercise protocols, and stress management techniques.
Be thorough, specific, and actionable in your premium insights.`
        },
        {
          role: 'user',
          content: prompt
        }
      ],
      max_tokens: 3000,
      temperature: 0.7
    })

    return completion.choices[0].message.content
  } catch (error) {
    console.error('OpenAI Premium API error:', error)
    return basicInsight + '\n\n[Premium upgrade: Extended analysis unavailable at this time]'
  }
}

function buildPremiumPrompt(basicInsight, answers, scores) {
  return `EXPAND upon this basic wellness insight to create a comprehensive premium report:

${basicInsight}

Provide additional premium content:
1. A detailed 7-day wellness improvement plan
2. Specific meal suggestions for each day
3. Exercise recommendations with duration and intensity
4. Sleep hygiene checklist
5. Stress management techniques tailored to their stress level
6. Habit stacking suggestions for long-term success
7. Warning signs to watch for and when to seek professional help`
}
